FROM postgres:16

# Copiar scripts de inicialización SQL
COPY ./postgres/generated/*.sql /docker-entrypoint-initdb.d/

# Crear wrapper del entrypoint que limpia variables después de inicializar
RUN echo '#!/bin/bash' > /usr/local/bin/secure-entrypoint.sh && \
    echo 'set -e' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '# Ejecutar el entrypoint original de postgres' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '/usr/local/bin/docker-entrypoint.sh postgres &' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'PG_PID=$!' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '# Esperar a que postgres inicialice' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'sleep 10' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '# Limpiar variables de entorno sensibles del proceso' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'unset POSTGRES_PASSWORD' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'unset POSTGRES_USER' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'unset POSTGRES_DB' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '' >> /usr/local/bin/secure-entrypoint.sh && \
    echo '# Esperar a que el proceso de postgres termine' >> /usr/local/bin/secure-entrypoint.sh && \
    echo 'wait $PG_PID' >> /usr/local/bin/secure-entrypoint.sh && \
    chmod +x /usr/local/bin/secure-entrypoint.sh && \
    chmod 644 /docker-entrypoint-initdb.d/*.sql

ENTRYPOINT ["/usr/local/bin/secure-entrypoint.sh"]
CMD []